language: node_js
node_js:
- '0.12'
script:
- npm test --coverage
- npm run-script coveralls
env:
  global:
    secure: VzkZvd0TM1m40yfahQKc5ITa/843l8BB0Sr8fA7O0RcMECTg/xBlWU4Paby2V+JWumgCJDx5YvxLlAdHeUaCWDkGlbJLPu8uPSRMZHRNH3PN2TNogNtruXmb9Z1ORZc5CwLNstWdK4MzMqErevPTxCxJ03scuzZxMiiEZpTOv+aQLZ7jEqTiA20q696QfsYpMvVB0XSpMEYqqFRdpMxGhf0QZ+bNlRN8h1SGw6ehw7jFKubQ1DozSKug10RU6aAGUHyaBisjc9tsSB1atJraeJUXSMucYD1L1oXWl0agE2RBSO8PAozwdJMoifHrVvQtW9cSuw9hPgiwd2qSNoH6IvhoIxeSEhqdVaS/0d22YKUxY+HkhYeIKCm+6kd0tcDfZ8+FqB7654ZhyIgCeOf1NcENu1OMaehbtKcALSBUi8yrDDVVntJFjBoKmPtdCAMq4iTL+28oBB7aDndUTjuyqEtPyN4qMY1R9bGcn/DMIwhBrRzIcM3MwPnn2S/+RUpr/NwyXXy7MgYXeVJE61sps/vA1JklwnRebL3c2nl/JZZrrWSaHquTMVDbkoxQHJhUR4vOQ/KzfQEQoqRZY9w/CO7HmVFMOo6RH3i5ZSNRN6YtOndGvUHFRmqIBf5iRaZiEgDb9xX1XmS4LzOR0dhHI3Gl/y3YAx8pbc7TeNrq4UQ=
