language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g eslint
  - eslint --reset -c ./eslintrc $(git --no-pager diff --name-only --relative FETCH_HEAD $(git merge-base FETCH_HEAD origin/HEAD) | grep "\.js$")
script: MOCHA_REPORTER=tap npm test --coverage
after_success:
- npm run coveralls
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1ec4245f90231619d30
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
